name: Bot Giochi Gratis

on:
  schedule:
    - cron: '0 10 * * *' # Gira ogni giorno alle 10:00
  workflow_dispatch: # Permette di lanciarlo a mano

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installa librerie
        run: pip install requests

      - name: Esegui il Bot
        env:
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py

      - name: Salva la memoria dei giochi
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add giochi_visti.txt || true
          git commit -m "Aggiorna cronologia giochi" || true
          git push || true
