name: Game Bot Cron

on:
  schedule:
    - cron: '30 10 * * *'  # Gira ogni giorno alle 10:30 UTC (11:30 italiane)
  workflow_dispatch:      # Mantiene il tasto per l'avvio manuale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codice
        uses: actions/checkout@v4 # Versione aggiornata

      - name: Setup Python
        uses: actions/setup-python@v5 # Versione aggiornata
        with:
          python-version: '3.9'

      - name: Install dipendenze
        run: pip install requests

      - name: Esegui Bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MY_PERSONAL_ID: ${{ secrets.MY_PERSONAL_ID }}
        run: python bot.py

      - name: Salva modifiche al database
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add sent_games.txt
          git commit -m "Update database: sent games list" || exit 0
          git push
