name: Game Bot Cron
on:
  schedule:
    - cron: '0 * * * *' # Gira ogni ora
  workflow_dispatch: # Permette l'avvio manuale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codice
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dipendenze
        run: pip install requests
      - name: Esegui Bot
        run: python bot.py
      - name: Salva modifiche al file di testo
        run: |
          git config --global user.name 'GameBot'
          git config --global user.email 'bot@noreply.github.com'
          git add sent_games.txt
          git commit -m "Update sent games list" || exit 0
          git push
